name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  format-and-lint:
    name: Format & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install black flake8 isort mypy

      - name: Check formatting (Black)
        run: black --check src/ tests/

      - name: Lint with Flake8
        run: flake8 src/ tests/

      - name: Check imports (isort)
        run: isort --check-only src/ tests/

      - name: Static type checking (mypy)
        run: mypy src/*.py tests/*.py

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Run tests with pytest
        run: poetry run pytest tests/ -v
